server:
  port: 30405

# spring 配置
spring:
  application:
    name: alinesno-infra-ops-watcher-boot
    id: 1879095534591475712
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_ops_watcher_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.ops.watcher.entity;
  database:
    type: mysql
  index:
    prefix: alinesno_ops_watcher_idx_
  unique:
    prefix: alinesno_ops_watcher_uni_

# wechat token
alinesno:
  security:
    # 排除路径
    excludes:
      - /sso/**
      - /logout
  infra:
    gateway:
      host: http://alinesno-infra-base-gateway-proxy-application.beta.base.infra.linesno.com
  data:
    scheduler:
      workspacePath: ${user.home}/.infra-data-scheduler

# sa-token配置
sa-token:
  token-name: Authorization
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
